version: '2'

services:
  bridge:
    image: mgbi/bitbucket-teamworkchat-bridge
    environment:
      BRIDGE_LISTEN_ADDR: ${BRIDGE_LISTEN_ADDR}
      BRIDGE_LISTEN_PORT: ${BRIDGE_LISTEN_PORT}
      TEAMWORK_PROJECT_BASE_URL: ${TEAMWORK_PROJECT_BASE_URL}

      BITBUCKET_PROJECT_KEY_1: ${BITBUCKET_PROJECT_KEY_1}
      TEAMWORK_PROJECT_ID_1: ${TEAMWORK_PROJECT_ID_1}
      TEAMWORK_CHAT_CHANNEL_ID_1: ${TEAMWORK_CHAT_CHANNEL_ID_1}

      BITBUCKET_PROJECT_KEY_2: ${BITBUCKET_PROJECT_KEY_2}
      TEAMWORK_PROJECT_ID_2: ${TEAMWORK_PROJECT_ID_2}
      TEAMWORK_CHAT_CHANNEL_ID_2: ${TEAMWORK_CHAT_CHANNEL_ID_2}

      BITBUCKET_USER_NICKNAME_1: ${BITBUCKET_USER_NICKNAME_1}
      TEAMWORK_USER_ID_1: ${TEAMWORK_USER_ID_1}
      TEAMWORK_USER_TOKEN_1: ${TEAMWORK_USER_TOKEN_1}

      BITBUCKET_USER_NICKNAME_2: ${BITBUCKET_USER_NICKNAME_2}
      TEAMWORK_USER_ID_2: ${TEAMWORK_USER_ID_2}
      TEAMWORK_USER_TOKEN_2: ${TEAMWORK_USER_TOKEN_2}

      BITBUCKET_USER_NICKNAME_3: ${BITBUCKET_USER_NICKNAME_3}
      TEAMWORK_USER_ID_3: ${TEAMWORK_USER_ID_3}
      TEAMWORK_USER_TOKEN_3: ${TEAMWORK_USER_TOKEN_3}

      BITBUCKET_USER_NICKNAME_4: ${BITBUCKET_USER_NICKNAME_4}
      TEAMWORK_USER_ID_4: ${TEAMWORK_USER_ID_4}
      TEAMWORK_USER_TOKEN_4: ${TEAMWORK_USER_TOKEN_4}

      BITBUCKET_USER_NICKNAME_5: ${BITBUCKET_USER_NICKNAME_5}
      TEAMWORK_USER_ID_5: ${TEAMWORK_USER_ID_5}
      TEAMWORK_USER_TOKEN_5: ${TEAMWORK_USER_TOKEN_5}

      TEAMWORK_CI_USER_TOKEN: ${TEAMWORK_CI_USER_TOKEN}
    ports:
    - ${EXTERNAL_BRIDGE_LISTEN_PORT}:${BRIDGE_LISTEN_PORT}
