version: '2'

services:
  bridge:
    image: mgbi/bitbucket-teamworkchat-bridge
    environment:
      BRIDGE_LISTEN_ADDR: ${BRIDGE_LISTEN_ADDR}
      BRIDGE_LISTEN_PORT: ${BRIDGE_LISTEN_PORT}
      TEAMWORK_CHAT_HOOK: ${TEAMWORK_CHAT_HOOK}

      BITBUCKET_PROJECT_KEY_1: ${BITBUCKET_PROJECT_KEY_1}
      TEAMWORK_CHAT_CHANNEL_ID_1: ${TEAMWORK_CHAT_CHANNEL_ID_1}
      BITBUCKET_PROJECT_KEY_2: ${BITBUCKET_PROJECT_KEY_2}
      TEAMWORK_CHAT_CHANNEL_ID_2: ${TEAMWORK_CHAT_CHANNEL_ID_2}

      BITBUCKET_USER_NICKNAME_1: ${BITBUCKET_USER_NICKNAME_1}
      TEAMWORK_USER_TOKEN_1: ${TEAMWORK_USER_TOKEN_1}
      BITBUCKET_USER_NICKNAME_2: ${BITBUCKET_USER_NICKNAME_2}
      TEAMWORK_USER_TOKEN_2: ${TEAMWORK_USER_TOKEN_2}
    ports:
    - 8002:5000
